<?php
/**
 * ConfluencePageRepresentationVersion
 *
 * PHP version 5
 *
 * @category Class
 * @package  ConfluenceClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Confluence Rest Resources
 *
 * This is the confluence rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 6.15.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConfluenceClient\Model;

use \ArrayAccess;
use \ConfluenceClient\ObjectSerializer;

/**
 * ConfluencePageRepresentationVersion Class Doc Comment
 *
 * @category Class
 * @package  ConfluenceClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfluencePageRepresentationVersion implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'confluencePageRepresentation_version';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'by' => '\ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedBy',
        'when' => 'string',
        'message' => 'string',
        'number' => 'float',
        'minor_edit' => 'bool',
        'hidden' => 'bool',
        '_links' => '\ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedByLinks',
        '_expandable' => '\ConfluenceClient\Model\ConfluencePageRepresentationVersionExpandable'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'by' => null,
        'when' => null,
        'message' => null,
        'number' => null,
        'minor_edit' => null,
        'hidden' => null,
        '_links' => null,
        '_expandable' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'by' => 'by',
        'when' => 'when',
        'message' => 'message',
        'number' => 'number',
        'minor_edit' => 'minorEdit',
        'hidden' => 'hidden',
        '_links' => '_links',
        '_expandable' => '_expandable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'by' => 'setBy',
        'when' => 'setWhen',
        'message' => 'setMessage',
        'number' => 'setNumber',
        'minor_edit' => 'setMinorEdit',
        'hidden' => 'setHidden',
        '_links' => 'setLinks',
        '_expandable' => 'setExpandable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'by' => 'getBy',
        'when' => 'getWhen',
        'message' => 'getMessage',
        'number' => 'getNumber',
        'minor_edit' => 'getMinorEdit',
        'hidden' => 'getHidden',
        '_links' => 'getLinks',
        '_expandable' => 'getExpandable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['by'] = isset($data['by']) ? $data['by'] : null;
        $this->container['when'] = isset($data['when']) ? $data['when'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['minor_edit'] = isset($data['minor_edit']) ? $data['minor_edit'] : null;
        $this->container['hidden'] = isset($data['hidden']) ? $data['hidden'] : null;
        $this->container['_links'] = isset($data['_links']) ? $data['_links'] : null;
        $this->container['_expandable'] = isset($data['_expandable']) ? $data['_expandable'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['by'] === null) {
            $invalidProperties[] = "'by' can't be null";
        }
        if ($this->container['when'] === null) {
            $invalidProperties[] = "'when' can't be null";
        }
        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ($this->container['minor_edit'] === null) {
            $invalidProperties[] = "'minor_edit' can't be null";
        }
        if ($this->container['hidden'] === null) {
            $invalidProperties[] = "'hidden' can't be null";
        }
        if ($this->container['_links'] === null) {
            $invalidProperties[] = "'_links' can't be null";
        }
        if ($this->container['_expandable'] === null) {
            $invalidProperties[] = "'_expandable' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets by
     *
     * @return \ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedBy
     */
    public function getBy()
    {
        return $this->container['by'];
    }

    /**
     * Sets by
     *
     * @param \ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedBy $by by
     *
     * @return $this
     */
    public function setBy($by)
    {
        $this->container['by'] = $by;

        return $this;
    }

    /**
     * Gets when
     *
     * @return string
     */
    public function getWhen()
    {
        return $this->container['when'];
    }

    /**
     * Sets when
     *
     * @param string $when when
     *
     * @return $this
     */
    public function setWhen($when)
    {
        $this->container['when'] = $when;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message message
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets number
     *
     * @return float
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param float $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets minor_edit
     *
     * @return bool
     */
    public function getMinorEdit()
    {
        return $this->container['minor_edit'];
    }

    /**
     * Sets minor_edit
     *
     * @param bool $minor_edit minor_edit
     *
     * @return $this
     */
    public function setMinorEdit($minor_edit)
    {
        $this->container['minor_edit'] = $minor_edit;

        return $this;
    }

    /**
     * Gets hidden
     *
     * @return bool
     */
    public function getHidden()
    {
        return $this->container['hidden'];
    }

    /**
     * Sets hidden
     *
     * @param bool $hidden hidden
     *
     * @return $this
     */
    public function setHidden($hidden)
    {
        $this->container['hidden'] = $hidden;

        return $this;
    }

    /**
     * Gets _links
     *
     * @return \ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedByLinks
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param \ConfluenceClient\Model\ConfluencePageRepresentationHistoryCreatedByLinks $_links _links
     *
     * @return $this
     */
    public function setLinks($_links)
    {
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets _expandable
     *
     * @return \ConfluenceClient\Model\ConfluencePageRepresentationVersionExpandable
     */
    public function getExpandable()
    {
        return $this->container['_expandable'];
    }

    /**
     * Sets _expandable
     *
     * @param \ConfluenceClient\Model\ConfluencePageRepresentationVersionExpandable $_expandable _expandable
     *
     * @return $this
     */
    public function setExpandable($_expandable)
    {
        $this->container['_expandable'] = $_expandable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


