<?php
/**
 * ConfluenceSpaceErrorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ConfluenceClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Confluence Rest Resources
 *
 * This is the confluence rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ConfluenceClient;

use PHPUnit\Framework\TestCase;

/**
 * ConfluenceSpaceErrorTest Class Doc Comment
 *
 * @category    Class
 * @description ConfluenceSpaceError
 * @package     ConfluenceClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConfluenceSpaceErrorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConfluenceSpaceError"
     */
    public function testConfluenceSpaceError()
    {
    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }
}
