<?php
/**
 * ConfluencePageExistsHistoryExpandableTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ConfluenceClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Confluence Rest Resources
 *
 * This is the confluence rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 6.15.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ConfluenceClient;

use PHPUnit\Framework\TestCase;

/**
 * ConfluencePageExistsHistoryExpandableTest Class Doc Comment
 *
 * @category    Class
 * @description ConfluencePageExistsHistoryExpandable
 * @package     ConfluenceClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConfluencePageExistsHistoryExpandableTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConfluencePageExistsHistoryExpandable"
     */
    public function testConfluencePageExistsHistoryExpandable()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "previous_version"
     */
    public function testPropertyPreviousVersion()
    {
    }

    /**
     * Test attribute "contributors"
     */
    public function testPropertyContributors()
    {
    }

    /**
     * Test attribute "next_version"
     */
    public function testPropertyNextVersion()
    {
    }
}
